CRITICAL - 2021-09-09 10:12:19 --> syntax error, unexpected '}', expecting ';' or ','
#0 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(273): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\laragon\\www\\...')
#1 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(247): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(885): class_exists('\\App\\Controller...', true)
#5 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(421): CodeIgniter\CodeIgniter->startController()
#6 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\v1\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-09-09 12:07:26 --> Unknown column 'users.deleted_at' in 'where clause'
CRITICAL - 2021-09-09 12:07:26 --> Unknown column 'users.deleted_at' in 'where clause'
#0 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('SELECT *\nFROM `...')
#1 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Model.php(228): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\v1\vendor\codeigniter4\framework\system\BaseModel.php(644): CodeIgniter\Model->doFirst()
#6 C:\laragon\www\v1\app\Models\UserModel.php(73): CodeIgniter\BaseModel->first()
#7 C:\laragon\www\v1\app\Controllers\Auth\login.php(40): App\Models\UserModel->getUserBy('email', 'f@centrogeo.edu...')
#8 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Auth\login->sigin()
#9 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\login))
#10 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\v1\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2021-09-09 12:20:49 --> Unknown column 'users.deleted_at' in 'where clause'
CRITICAL - 2021-09-09 12:20:49 --> Unknown column 'users.deleted_at' in 'where clause'
#0 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('SELECT *\nFROM `...')
#1 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Model.php(228): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\v1\vendor\codeigniter4\framework\system\BaseModel.php(644): CodeIgniter\Model->doFirst()
#6 C:\laragon\www\v1\app\Models\UserModel.php(73): CodeIgniter\BaseModel->first()
#7 C:\laragon\www\v1\app\Controllers\Auth\login.php(41): App\Models\UserModel->getUserBy('email', 'f@centrogeo.edu...')
#8 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Auth\login->sigin()
#9 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\login))
#10 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\v1\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2021-09-09 12:21:12 --> Unknown column 'users.deleted_at' in 'where clause'
CRITICAL - 2021-09-09 12:21:12 --> Unknown column 'users.deleted_at' in 'where clause'
#0 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('SELECT *\nFROM `...')
#1 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Model.php(228): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\v1\vendor\codeigniter4\framework\system\BaseModel.php(644): CodeIgniter\Model->doFirst()
#6 C:\laragon\www\v1\app\Models\UserModel.php(73): CodeIgniter\BaseModel->first()
#7 C:\laragon\www\v1\app\Controllers\Auth\login.php(41): App\Models\UserModel->getUserBy('email', 'jfkjf@centrogeo...')
#8 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Auth\login->sigin()
#9 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\login))
#10 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\v1\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2021-09-09 12:28:30 --> Unknown column 'users.deleted_at' in 'where clause'
CRITICAL - 2021-09-09 12:28:30 --> Unknown column 'users.deleted_at' in 'where clause'
#0 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('SELECT *\nFROM `...')
#1 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Model.php(228): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\v1\vendor\codeigniter4\framework\system\BaseModel.php(644): CodeIgniter\Model->doFirst()
#6 C:\laragon\www\v1\app\Models\UserModel.php(74): CodeIgniter\BaseModel->first()
#7 C:\laragon\www\v1\app\Controllers\Auth\login.php(41): App\Models\UserModel->getUserBy('email', 'jfkjf@centrogeo...')
#8 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Auth\login->sigin()
#9 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\login))
#10 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\v1\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-09-09 12:30:37 --> Array to string conversion
#0 C:\laragon\www\v1\app\Views\Auth\login.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\laragon\\www\\...', 19, Array)
#1 C:\laragon\www\v1\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\laragon\\www\\...')
#2 C:\laragon\www\v1\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('Auth/login.php', Array, true)
#4 C:\laragon\www\v1\app\Controllers\Auth\login.php(21): view('Auth/login.php')
#5 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Auth\login->index()
#6 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\login))
#7 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\v1\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2021-09-09 12:45:31 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2021-09-09 12:45:31 --> Unknown column 'created_at' in 'field list'
#0 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\v1\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\v1\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#8 C:\laragon\www\v1\app\Controllers\Auth\Register.php(55): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#9 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Auth\Register->store()
#10 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Register))
#11 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\v1\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-09 12:46:05 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2021-09-09 12:46:05 --> Unknown column 'updated_at' in 'field list'
#0 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\v1\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\v1\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#8 C:\laragon\www\v1\app\Controllers\Auth\Register.php(55): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#9 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Auth\Register->store()
#10 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Register))
#11 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\v1\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-09 22:49:43 --> Duplicate entry 'AlejandroVega1' for key 'username_UNIQUE'
CRITICAL - 2021-09-09 22:49:43 --> Duplicate entry 'AlejandroVega1' for key 'username_UNIQUE'
#0 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\v1\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\v1\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#8 C:\laragon\www\v1\app\Controllers\Auth\Register.php(56): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#9 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Auth\Register->store()
#10 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Register))
#11 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\v1\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-09 22:49:52 --> Duplicate entry 'AlejandroVega3' for key 'username_UNIQUE'
CRITICAL - 2021-09-09 22:49:52 --> Duplicate entry 'AlejandroVega3' for key 'username_UNIQUE'
#0 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\v1\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\v1\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#8 C:\laragon\www\v1\app\Controllers\Auth\Register.php(56): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#9 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Auth\Register->store()
#10 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Register))
#11 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\v1\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-09 22:49:57 --> Duplicate entry 'AlejandroVega5' for key 'username_UNIQUE'
CRITICAL - 2021-09-09 22:49:57 --> Duplicate entry 'AlejandroVega5' for key 'username_UNIQUE'
#0 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\v1\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\v1\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#8 C:\laragon\www\v1\app\Controllers\Auth\Register.php(56): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#9 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Auth\Register->store()
#10 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Register))
#11 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\v1\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2021-09-09 22:50:00 --> Cannot add or update a child row: a foreign key constraint fails (`usuarios`.`users_info`, CONSTRAINT `FK1Users_to_usersinfo` FOREIGN KEY (`users_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
CRITICAL - 2021-09-09 22:50:00 --> Cannot add or update a child row: a foreign key constraint fails (`usuarios`.`users_info`, CONSTRAINT `FK1Users_to_usersinfo` FOREIGN KEY (`users_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
#0 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `us...')
#1 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\v1\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\v1\app\Models\UserModel.php(39): CodeIgniter\Model->insert(Object(App\Entities\UserInfo))
#8 C:\laragon\www\v1\vendor\codeigniter4\framework\system\BaseModel.php(1541): App\Models\UserModel->storeUserInfo(Array)
#9 C:\laragon\www\v1\vendor\codeigniter4\framework\system\BaseModel.php(785): CodeIgniter\BaseModel->trigger('afterInsert', Array)
#10 C:\laragon\www\v1\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, false)
#11 C:\laragon\www\v1\vendor\codeigniter4\framework\system\BaseModel.php(687): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#12 C:\laragon\www\v1\app\Controllers\Auth\Register.php(56): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#13 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Auth\Register->store()
#14 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Register))
#15 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\laragon\www\v1\public\index.php(37): CodeIgniter\CodeIgniter->run()
#17 {main}
CRITICAL - 2021-09-09 23:01:49 --> Argument 2 passed to CodeIgniter\HTTP\RedirectResponse::route() must be of the type array, string given, called in C:\laragon\www\v1\app\Controllers\Auth\Register.php on line 69
#0 C:\laragon\www\v1\app\Controllers\Auth\Register.php(69): CodeIgniter\HTTP\RedirectResponse->route('login', 'alvero0309@gmai...')
#1 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Auth\Register->store()
#2 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Register))
#3 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\laragon\www\v1\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-09 23:09:24 --> Cannot unpack array with string keys
#0 C:\laragon\www\v1\app\Controllers\Auth\Register.php(69): CodeIgniter\HTTP\RedirectResponse->route('login', Array)
#1 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Auth\Register->store()
#2 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Register))
#3 C:\laragon\www\v1\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\laragon\www\v1\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
